### ISSUE TITLE
Conflict Between Optional and Required Rules

### ISSUE THREAD

**Issue by clementbirkle** [spatie/laravel-data#844]
**✏️ Describe the bug**
`Optional` should be skipped when a `Required` rule is applied (e.g., `RequireWith`, `RequiredIf`).

**↪️ To Reproduce**

```php

it('this test should create an error during validation', function () {

    class UpdateProductData extends Data
    {
        public function __construct(
            #[RequiredWith('discountValue')]
            public DiscountType $discountType = new Optional,
            #[RequiredWith('discountType')]
            public float $discountValue = new Optional,
        ) {
        }
    }

    dd(UpdateProductData::validateAndCreate(['discountValue' => 20));
});
```

**✅ Expected behavior**
In this test, I expect an error message like 'The discountType is required when discountValue is present.', because `discountValue` is provided but `discountType` is not.

The issue arises due to two points:

1. If a value is not provided for an optional type, the rule will be removed. This should not happen if the attribute has rules like `RequiredWith`, `RequiredIf`, etc.
2. The `SometimesRuleInferrer` should not add the `sometimes` rule when the attribute has rules like `RequiredWith`, `RequiredIf`, etc.

**🖥️ Versions**

Laravel: 11
Laravel Data: 4.8.1
PHP: 8.2

I can try to make a PR if you think this is an issue.

**Comment by rubenvanassche** [comment]
This should be fixed with the release later today

**Comment by clementbirkle** [comment]
Thank you, @rubenvanassche, but this doesn't fully solve the problem for me.

For example:

```php
it('this test should not create an error during validation', function () {

    class UpdateProductData extends Data
    {
        public function __construct(
            #[RequiredWith('discountValue')]
            public DiscountType $discountType = new Optional,
            #[RequiredWith('discountType')]
            public float $discountValue = new Optional,
        ) {
        }
    }

    dd(UpdateProductData::validateAndCreate([]));
});
```

This code currently throws an error, but it shouldn't, because neither `discountType` nor `discountValue` are provided. In this case, the `Sometime` rule shouldn't be removed.

**Comment by rubenvanassche** [comment]
I cannot reproduce that, you know you're missing the optional type in the properties?

**Comment by clementbirkle** [comment]
Sorry @rubenvanassche, my example was wrong!

Here is a correct example:

```php
it('this test should not create an error during validation', function () {

    class UpdateProductData extends Data
    {
        public function __construct(
            public string|Optional $type = new Optional,
            #[RequiredUnless('type', 'bundle')]
            public float|null|Optional $price = new Optional,
        ) {
        }
    }

    UpdateProductData::validateAndCreate([]);
});
```

This code currently throws an error, but it shouldn't, because neither `type` nor `price` are provided. In this case, the `Sometime` rule shouldn't be removed.

**Comment by rubenvanassche** [comment]
I think in this case you're better off by manually defining the rules since I don't see how we can model laravel data to make a sensible default without knowing the values at this point.
